/// Nomes em português para abreviações usadas em chaves de capítulo (ex.: GEN → Gênesis).
String bibleBookPortugueseName(String abbrevUpper) {
  const m = {
    'GEN': 'Gênesis',
    'EXO': 'Êxodo',
    'LEV': 'Levítico',
    'NUM': 'Números',
    'DEU': 'Deuteronômio',
    'JOS': 'Josué',
    'JDG': 'Juízes',
    'RUT': 'Rute',
    '1SA': '1 Samuel',
    '2SA': '2 Samuel',
    '1KI': '1 Reis',
    '2KI': '2 Reis',
    '1CH': '1 Crônicas',
    '2CH': '2 Crônicas',
    'EZR': 'Esdras',
    'NEH': 'Neemias',
    'EST': 'Ester',
    'JOB': 'Jó',
    'PSA': 'Salmos',
    'PRO': 'Provérbios',
    'ECC': 'Eclesiastes',
    'SNG': 'Cânticos',
    'ISA': 'Isaías',
    'JER': 'Jeremias',
    'LAM': 'Lamentações',
    'EZK': 'Ezequiel',
    'DAN': 'Daniel',
    'HOS': 'Oséias',
    'JOE': 'Joel',
    'AMO': 'Amós',
    'OBA': 'Obadias',
    'JON': 'Jonas',
    'MIC': 'Miquéias',
    'NAM': 'Naum',
    'HAB': 'Habacuque',
    'ZEP': 'Sofonias',
    'HAG': 'Ageu',
    'ZEC': 'Zacarias',
    'MAL': 'Malaquias',
    'MAT': 'Mateus',
    'MRK': 'Marcos',
    'LUK': 'Lucas',
    'JHN': 'João',
    'ACT': 'Atos',
    'ROM': 'Romanos',
    '1CO': '1 Coríntios',
    '2CO': '2 Coríntios',
    'GAL': 'Gálatas',
    'EPH': 'Efésios',
    'PHP': 'Filipenses',
    'COL': 'Colossenses',
    '1TH': '1 Tessalonicenses',
    '2TH': '2 Tessalonicenses',
    '1TI': '1 Timóteo',
    '2TI': '2 Timóteo',
    'TIT': 'Tito',
    'PHM': 'Filemom',
    'HEB': 'Hebreus',
    'JAS': 'Tiago',
    '1PE': '1 Pedro',
    '2PE': '2 Pedro',
    '1JN': '1 João',
    '2JN': '2 João',
    '3JN': '3 João',
    'JUD': 'Judas',
    'REV': 'Apocalipse',
  };
  return m[abbrevUpper.toUpperCase()] ?? abbrevUpper;
}
